default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Doanhnhan
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: book_car

test:
  <<: *default
  database: book_car_test

production:
  <<: *default
  adapter: mysql2
  database: book_car_v2_production
